# Generated by Django 5.2.16 on 2026-09-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
